version: 2

multi-ecosystem-groups:
  # Default (Branch) Infrastructure Update
  infrastructure:
    schedule:
      interval: "weekly"
      target-branch: dev

  flutter:
    schedule:
      interval: "weekly"
      target-branch: dev
  
  compose:
    schedule:
      interval: "daily"
      target-branch: compose-dev

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns:
      - "*"
    
  - package-ecosystem: "npm"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns:
      - "*"
    
  - package-ecosystem: "pub"
    directory: "/"
    multi-ecosystem-group: "flutter"
    patterns:
      - "*"
    
  - package-ecosystem: "gradle"
    directory: "/android"
    multi-ecosystem-group: "flutter"
    patterns:
      - "*"
    
  - package-ecosystem: "gradle"
    labels: [ "ReVanced Manager Compose" ]
    directory: /
    multi-ecosystem-group: "compose"
    patterns:
      - "*"
