version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

  flutter:
    schedule:
      interval: "weekly"
  
  compose:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    multi-ecosystem-group: "infrastructure"
  
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: dev
    multi-ecosystem-group: "infrastructure"
    
  - package-ecosystem: "pub"
    directory: "/"
    target-branch: dev
    multi-ecosystem-group: "flutter"

  - package-ecosystem: "gradle"
    directory: "/android"
    target-branch: dev
    multi-ecosystem-group: "flutter"
    
  - package-ecosystem: "gradle"
    labels: [ "ReVanced Manager Compose" ]
    directory: /
    target-branch: compose-dev
    multi-ecosystem-group: "compose"
