version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
  
  full-stack:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
  
  - package-ecosystem: "terraform"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "npm"
    directory: "/frontend"
    multi-ecosystem-group: "full-stack"
    
  - package-ecosystem: "bundler"
    directory: "/backend"
    multi-ecosystem-group: "full-stack"
